# Generated by Django 3.1.2 on 2020-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('Area', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
    ]
