# Generated by Django 3.1.2 on 2020-11-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20201109_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
    ]
