# Generated by Django 2.2.16 on 2020-11-19 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Area',
            field=models.CharField(default='Temp', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='doctor_id',
            field=models.CharField(default='Not doctor', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='full_name',
            field=models.CharField(default='NoName', max_length=264),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(default=1022102112, max_length=10),
        ),
    ]
