# Generated by Django 2.2.16 on 2020-11-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_auto_20201119_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_doctor',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
