# Generated by Django 2.2.16 on 2020-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_userprofileinfo_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
