# Generated by Django 2.2.16 on 2020-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0002_auto_20201112_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
