# Generated by Django 2.2.16 on 2020-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0005_auto_20201122_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.URLField(default='https://www.temporary.com'),
        ),
    ]
