# Generated by Django 2.2.16 on 2020-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0006_files_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='files',
            name='url',
        ),
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='files',
            name='uploadedfiles',
            field=models.FileField(null=True, upload_to='useruploadedfiles'),
        ),
    ]
