# Generated by Django 2.2.16 on 2020-12-07 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0007_auto_20201207_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections_existed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 11, 43, 41, 914300)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
