# Generated by Django 2.2.16 on 2020-12-10 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_page', '0008_auto_20201207_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='via_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connections_existed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 18, 34, 234895)),
        ),
        migrations.CreateModel(
            name='connection_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 18, 34, 235257))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
