# Generated by Django 2.2.16 on 2020-12-10 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0009_auto_20201210_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users_page.connection_api'),
        ),
        migrations.AlterField(
            model_name='connection_api',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 21, 29, 294810)),
        ),
        migrations.AlterField(
            model_name='connections_existed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 21, 29, 295842)),
        ),
    ]
