# Generated by Django 2.2.16 on 2020-12-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0011_auto_20201210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_api',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 10, 36, 8, 938547)),
        ),
        migrations.AlterField(
            model_name='connections_existed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 10, 36, 8, 939481)),
        ),
    ]
