# Generated by Django 2.2.16 on 2020-12-12 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0012_auto_20201212_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_api',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 12, 47, 48, 62553)),
        ),
        migrations.AlterField(
            model_name='connections_existed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 12, 47, 48, 63435)),
        ),
    ]
