# Generated by Django 2.2.16 on 2020-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Suggestion', models.BooleanField(default=False, verbose_name='Suggestion')),
                ('Is_Bug', models.BooleanField(default=False, verbose_name='Bug')),
                ('Is_Question', models.BooleanField(default=False, verbose_name='Question')),
                ('user_text', models.TextField(max_length=500)),
                ('user_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
