# Generated by Django 2.2.16 on 2020-11-11 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webpage',
            new_name='don_sub',
        ),
    ]
