# Generated by Django 2.2.16 on 2020-11-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20201111_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don_sub',
            name='url',
        ),
    ]
