# Generated by Django 2.2.16 on 2020-11-17 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_remove_don_sub_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_sub',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
