# Generated by Django 2.2.16 on 2020-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20201117_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_sub',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
