# Generated by Django 2.2.16 on 2020-12-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='med_ch',
            field=models.CharField(choices=[('D', 'Morning'), ('A', 'AfterNoon'), ('N', 'Night')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_ch_1',
            field=models.CharField(choices=[('D', 'Morning'), ('A', 'AfterNoon'), ('N', 'Night')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_ch_2',
            field=models.CharField(choices=[('D', 'Morning'), ('A', 'AfterNoon'), ('N', 'Night')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_co',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 10, 36, 8, 979134)),
        ),
    ]
