# Generated by Django 2.2.16 on 2020-12-12 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_auto_20201212_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='med_ch',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='med_ch_1',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='med_ch_2',
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_1_an',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_1_mrg',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_1_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_2_an',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_2_mrg',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_2_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_3_an',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_3_mrg',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_3_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_4_an',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_4_mrg',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_4_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_an',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_mrg',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='me_ch_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_1_co',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_2_co',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_3_co',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_4_co',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 12, 47, 48, 111242)),
        ),
    ]
